# Generated by Django 4.2.11 on 2025-12-21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproductionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('insemination', 'Insémination'), ('saillie', 'Saillie'), ('gestation_check', 'Contrôle gestation'), ('mise_bas', 'Mise bas')], max_length=20)),
                ('gestation_days', models.PositiveIntegerField(blank=True, null=True)),
                ('born_alive', models.PositiveIntegerField(default=0)),
                ('born_dead', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproduction_events', to='core.lot')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
