# Generated by Django 4.2.11 on 2025-12-21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reproduction_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('cost', 'Cost'), ('revenue', 'Revenue')], max_length=10)),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('vet', 'Vet'), ('labor', 'Labor'), ('sale', 'Sale'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_entries', to='core.farm')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='core.lot')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
